# Generated by Django 5.2.3 on 2025-07-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='work_summary',
            field=models.TextField(null=True),
        ),
    ]
