# Generated by Django 5.2.3 on 2025-07-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_description_remove_task_title_task_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours',
            field=models.CharField(null=True),
        ),
    ]
