# Generated by Django 5.2.3 on 2025-07-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_by',
        ),
    ]
